// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apimasteryproject_bikes.Context;

namespace apimasteryproject_bikes.Migrations
{
    [DbContext(typeof(BikeContext))]
    [Migration("20191112214656_first-migratin")]
    partial class firstmigratin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apimasteryproject_bikes.Models.Bicycle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<int>("ManufacturerID");

                    b.Property<string>("Name");

                    b.Property<string>("Style");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Bicycles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Description",
                            Image = "Image",
                            ManufacturerID = 1,
                            Name = "Tarmac",
                            Style = "Road"
                        });
                });

            modelBuilder.Entity("apimasteryproject_bikes.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Description",
                            Logo = "Logo",
                            Name = "Specialized"
                        });
                });

            modelBuilder.Entity("apimasteryproject_bikes.Models.Bicycle", b =>
                {
                    b.HasOne("apimasteryproject_bikes.Models.Manufacturer", "Manufacturers")
                        .WithMany("Bicycles")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
